// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: pyth-handler.proto

package server

import (
	"context"

	"pyth-go/app/pyth-handler/rpc/internal/logic"
	"pyth-go/app/pyth-handler/rpc/internal/svc"
	"pyth-go/app/pyth-handler/rpc/pb/pythhanlder"
)

type PythHandlerServer struct {
	svcCtx *svc.ServiceContext
	pythhanlder.UnimplementedPythHandlerServer
}

func NewPythHandlerServer(svcCtx *svc.ServiceContext) *PythHandlerServer {
	return &PythHandlerServer{
		svcCtx: svcCtx,
	}
}

func (s *PythHandlerServer) Ping(ctx context.Context, in *pythhanlder.PingRequest) (*pythhanlder.PongResponse, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
