// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.6

package app

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sendAccountFieldNames          = builder.RawFieldNames(&SendAccount{})
	sendAccountRows                = strings.Join(sendAccountFieldNames, ",")
	sendAccountRowsExpectAutoSet   = strings.Join(stringx.Remove(sendAccountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sendAccountRowsWithPlaceHolder = strings.Join(stringx.Remove(sendAccountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sendAccountModel interface {
		Insert(ctx context.Context, data *SendAccount) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SendAccount, error)
		Update(ctx context.Context, data *SendAccount) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSendAccountModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SendAccount struct {
		Id         int64  `db:"id"`
		SendChanel string `db:"send_chanel"` // 发送渠道
		Config     string `db:"config"`      // 账户配置
		Title      string `db:"title"`       // 账号名称
	}
)

func newSendAccountModel(conn sqlx.SqlConn) *defaultSendAccountModel {
	return &defaultSendAccountModel{
		conn:  conn,
		table: "`send_account`",
	}
}

func (m *defaultSendAccountModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSendAccountModel) FindOne(ctx context.Context, id int64) (*SendAccount, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sendAccountRows, m.table)
	var resp SendAccount
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSendAccountModel) Insert(ctx context.Context, data *SendAccount) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, sendAccountRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SendChanel, data.Config, data.Title)
	return ret, err
}

func (m *defaultSendAccountModel) Update(ctx context.Context, data *SendAccount) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sendAccountRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.SendChanel, data.Config, data.Title, data.Id)
	return err
}

func (m *defaultSendAccountModel) tableName() string {
	return m.table
}
